// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// matrixMultiply
NumericMatrix matrixMultiply(NumericMatrix mat1, NumericMatrix mat2);
RcppExport SEXP _CARBayesCopula_matrixMultiply(SEXP mat1SEXP, SEXP mat2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat1(mat1SEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat2(mat2SEXP);
    rcpp_result_gen = Rcpp::wrap(matrixMultiply(mat1, mat2));
    return rcpp_result_gen;
END_RCPP
}
// getDiagonal
NumericVector getDiagonal(NumericMatrix mat);
RcppExport SEXP _CARBayesCopula_getDiagonal(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(getDiagonal(mat));
    return rcpp_result_gen;
END_RCPP
}
// linpredcompute
NumericVector linpredcompute(NumericMatrix X, const int nsites, const int p, NumericVector beta, NumericVector offset);
RcppExport SEXP _CARBayesCopula_linpredcompute(SEXP XSEXP, SEXP nsitesSEXP, SEXP pSEXP, SEXP betaSEXP, SEXP offsetSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    rcpp_result_gen = Rcpp::wrap(linpredcompute(X, nsites, p, beta, offset));
    return rcpp_result_gen;
END_RCPP
}
// binomialbetaupdateRW
List binomialbetaupdateRW(NumericMatrix X, const int nsites, const int p, NumericVector beta, NumericVector offset, NumericVector y, NumericVector failures, NumericVector prior_meanbeta, NumericVector prior_varbeta, const int nblock, double beta_tune, List block_list);
RcppExport SEXP _CARBayesCopula_binomialbetaupdateRW(SEXP XSEXP, SEXP nsitesSEXP, SEXP pSEXP, SEXP betaSEXP, SEXP offsetSEXP, SEXP ySEXP, SEXP failuresSEXP, SEXP prior_meanbetaSEXP, SEXP prior_varbetaSEXP, SEXP nblockSEXP, SEXP beta_tuneSEXP, SEXP block_listSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type p(pSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type offset(offsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericVector >::type failures(failuresSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_meanbeta(prior_meanbetaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_varbeta(prior_varbetaSEXP);
    Rcpp::traits::input_parameter< const int >::type nblock(nblockSEXP);
    Rcpp::traits::input_parameter< double >::type beta_tune(beta_tuneSEXP);
    Rcpp::traits::input_parameter< List >::type block_list(block_listSEXP);
    rcpp_result_gen = Rcpp::wrap(binomialbetaupdateRW(X, nsites, p, beta, offset, y, failures, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list));
    return rcpp_result_gen;
END_RCPP
}
// binomialmcarupdateRW
List binomialmcarupdateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericMatrix Y, NumericMatrix failures, NumericMatrix phioffset, NumericVector denoffset, NumericMatrix Sigmainv, double rho, double phi_tune);
RcppExport SEXP _CARBayesCopula_binomialmcarupdateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP YSEXP, SEXP failuresSEXP, SEXP phioffsetSEXP, SEXP denoffsetSEXP, SEXP SigmainvSEXP, SEXP rhoSEXP, SEXP phi_tuneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type failures(failuresSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phioffset(phioffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigmainv(SigmainvSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type phi_tune(phi_tuneSEXP);
    rcpp_result_gen = Rcpp::wrap(binomialmcarupdateRW(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, Sigmainv, rho, phi_tune));
    return rcpp_result_gen;
END_RCPP
}
// mcarrhoupdateRW
List mcarrhoupdateRW(Rcpp::NumericMatrix Wstar, Rcpp::NumericVector Wstar_val, int K, int J, double rho, Rcpp::NumericMatrix Q, double det_Q, double proposal_sd_rho, Rcpp::NumericMatrix phi, Rcpp::NumericMatrix Sigma_inv);
RcppExport SEXP _CARBayesCopula_mcarrhoupdateRW(SEXP WstarSEXP, SEXP Wstar_valSEXP, SEXP KSEXP, SEXP JSEXP, SEXP rhoSEXP, SEXP QSEXP, SEXP det_QSEXP, SEXP proposal_sd_rhoSEXP, SEXP phiSEXP, SEXP Sigma_invSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Wstar(WstarSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type Wstar_val(Wstar_valSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< int >::type J(JSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Q(QSEXP);
    Rcpp::traits::input_parameter< double >::type det_Q(det_QSEXP);
    Rcpp::traits::input_parameter< double >::type proposal_sd_rho(proposal_sd_rhoSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type Sigma_inv(Sigma_invSEXP);
    rcpp_result_gen = Rcpp::wrap(mcarrhoupdateRW(Wstar, Wstar_val, K, J, rho, Q, det_Q, proposal_sd_rho, phi, Sigma_inv));
    return rcpp_result_gen;
END_RCPP
}
// gaussianmcarupdateRW
List gaussianmcarupdateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericMatrix phioffset, NumericVector denoffset, NumericMatrix Sigmainv, double rho, NumericVector nu2, double phi_tune);
RcppExport SEXP _CARBayesCopula_gaussianmcarupdateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP phioffsetSEXP, SEXP denoffsetSEXP, SEXP SigmainvSEXP, SEXP rhoSEXP, SEXP nu2SEXP, SEXP phi_tuneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phioffset(phioffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Sigmainv(SigmainvSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type nu2(nu2SEXP);
    Rcpp::traits::input_parameter< double >::type phi_tune(phi_tuneSEXP);
    rcpp_result_gen = Rcpp::wrap(gaussianmcarupdateRW(Wtriplet, Wbegfin, nsites, nvar, phi, phioffset, denoffset, Sigmainv, rho, nu2, phi_tune));
    return rcpp_result_gen;
END_RCPP
}
// ClaytonDensity
double ClaytonDensity(NumericVector LCDF, NumericVector CDF, double alpha, double nvar);
RcppExport SEXP _CARBayesCopula_ClaytonDensity(SEXP LCDFSEXP, SEXP CDFSEXP, SEXP alphaSEXP, SEXP nvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type LCDF(LCDFSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type CDF(CDFSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type nvar(nvarSEXP);
    rcpp_result_gen = Rcpp::wrap(ClaytonDensity(LCDF, CDF, alpha, nvar));
    return rcpp_result_gen;
END_RCPP
}
// binomialmcarupdateClaytonRW
List binomialmcarupdateClaytonRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericMatrix Y, NumericMatrix failures, NumericMatrix phioffset, NumericVector denoffset, NumericVector tau2, double alpha, double rho, double phi_tune);
RcppExport SEXP _CARBayesCopula_binomialmcarupdateClaytonRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP YSEXP, SEXP failuresSEXP, SEXP phioffsetSEXP, SEXP denoffsetSEXP, SEXP tau2SEXP, SEXP alphaSEXP, SEXP rhoSEXP, SEXP phi_tuneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type failures(failuresSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phioffset(phioffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type phi_tune(phi_tuneSEXP);
    rcpp_result_gen = Rcpp::wrap(binomialmcarupdateClaytonRW(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune));
    return rcpp_result_gen;
END_RCPP
}
// Claytontau2updateRW
List Claytontau2updateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, NumericVector prior_tau2, double tau2_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_Claytontau2updateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP prior_tau2SEXP, SEXP tau2_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_tau2(prior_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_tune(tau2_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Claytontau2updateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// ClaytonrhoupdateRW
List ClaytonrhoupdateRW(NumericMatrix Wtriplet, NumericVector Wtripletsum, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double rho_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_ClaytonrhoupdateRW(SEXP WtripletSEXP, SEXP WtripletsumSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP rho_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wtripletsum(WtripletsumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type rho_tune(rho_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(ClaytonrhoupdateRW(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// ClaytonalphaupdateRW
List ClaytonalphaupdateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double alpha_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_ClaytonalphaupdateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP alpha_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_tune(alpha_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(ClaytonalphaupdateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// FrankDensity
double FrankDensity(NumericVector CDF, double alpha, double nvar);
RcppExport SEXP _CARBayesCopula_FrankDensity(SEXP CDFSEXP, SEXP alphaSEXP, SEXP nvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type CDF(CDFSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type nvar(nvarSEXP);
    rcpp_result_gen = Rcpp::wrap(FrankDensity(CDF, alpha, nvar));
    return rcpp_result_gen;
END_RCPP
}
// binomialmcarupdateFrankRW
List binomialmcarupdateFrankRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericMatrix Y, NumericMatrix failures, NumericMatrix phioffset, NumericVector denoffset, NumericVector tau2, double alpha, double rho, double phi_tune);
RcppExport SEXP _CARBayesCopula_binomialmcarupdateFrankRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP YSEXP, SEXP failuresSEXP, SEXP phioffsetSEXP, SEXP denoffsetSEXP, SEXP tau2SEXP, SEXP alphaSEXP, SEXP rhoSEXP, SEXP phi_tuneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type failures(failuresSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phioffset(phioffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type phi_tune(phi_tuneSEXP);
    rcpp_result_gen = Rcpp::wrap(binomialmcarupdateFrankRW(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune));
    return rcpp_result_gen;
END_RCPP
}
// Franktau2updateRW
List Franktau2updateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, NumericVector prior_tau2, double tau2_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_Franktau2updateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP prior_tau2SEXP, SEXP tau2_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_tau2(prior_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_tune(tau2_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Franktau2updateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// FrankrhoupdateRW
List FrankrhoupdateRW(NumericMatrix Wtriplet, NumericVector Wtripletsum, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double rho_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_FrankrhoupdateRW(SEXP WtripletSEXP, SEXP WtripletsumSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP rho_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wtripletsum(WtripletsumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type rho_tune(rho_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(FrankrhoupdateRW(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// FrankalphaupdateRW
List FrankalphaupdateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double alpha_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_FrankalphaupdateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP alpha_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_tune(alpha_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(FrankalphaupdateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// GaussianDensity
double GaussianDensity(NumericVector CDF_q, double alpha, double nvar);
RcppExport SEXP _CARBayesCopula_GaussianDensity(SEXP CDF_qSEXP, SEXP alphaSEXP, SEXP nvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type CDF_q(CDF_qSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type nvar(nvarSEXP);
    rcpp_result_gen = Rcpp::wrap(GaussianDensity(CDF_q, alpha, nvar));
    return rcpp_result_gen;
END_RCPP
}
// binomialmcarupdateGaussianRW
List binomialmcarupdateGaussianRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericMatrix Y, NumericMatrix failures, NumericMatrix phioffset, NumericVector denoffset, NumericVector tau2, double alpha, double rho, double phi_tune);
RcppExport SEXP _CARBayesCopula_binomialmcarupdateGaussianRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP YSEXP, SEXP failuresSEXP, SEXP phioffsetSEXP, SEXP denoffsetSEXP, SEXP tau2SEXP, SEXP alphaSEXP, SEXP rhoSEXP, SEXP phi_tuneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type failures(failuresSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phioffset(phioffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type phi_tune(phi_tuneSEXP);
    rcpp_result_gen = Rcpp::wrap(binomialmcarupdateGaussianRW(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune));
    return rcpp_result_gen;
END_RCPP
}
// Gaussiantau2updateRW
List Gaussiantau2updateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, NumericVector prior_tau2, double tau2_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_Gaussiantau2updateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP prior_tau2SEXP, SEXP tau2_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_tau2(prior_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_tune(tau2_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Gaussiantau2updateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// GaussianrhoupdateRW
List GaussianrhoupdateRW(NumericMatrix Wtriplet, NumericVector Wtripletsum, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double rho_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_GaussianrhoupdateRW(SEXP WtripletSEXP, SEXP WtripletsumSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP rho_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wtripletsum(WtripletsumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type rho_tune(rho_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(GaussianrhoupdateRW(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// GaussianalphaupdateRW
List GaussianalphaupdateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double alpha_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_GaussianalphaupdateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP alpha_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_tune(alpha_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(GaussianalphaupdateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// GumbelDensity
double GumbelDensity(NumericVector LCDF, double alpha);
RcppExport SEXP _CARBayesCopula_GumbelDensity(SEXP LCDFSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type LCDF(LCDFSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(GumbelDensity(LCDF, alpha));
    return rcpp_result_gen;
END_RCPP
}
// binomialmcarupdateGumbelRW
List binomialmcarupdateGumbelRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericMatrix Y, NumericMatrix failures, NumericMatrix phioffset, NumericVector denoffset, NumericVector tau2, double alpha, double rho, double phi_tune);
RcppExport SEXP _CARBayesCopula_binomialmcarupdateGumbelRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP YSEXP, SEXP failuresSEXP, SEXP phioffsetSEXP, SEXP denoffsetSEXP, SEXP tau2SEXP, SEXP alphaSEXP, SEXP rhoSEXP, SEXP phi_tuneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type failures(failuresSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phioffset(phioffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type phi_tune(phi_tuneSEXP);
    rcpp_result_gen = Rcpp::wrap(binomialmcarupdateGumbelRW(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune));
    return rcpp_result_gen;
END_RCPP
}
// Gumbeltau2updateRW
List Gumbeltau2updateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, NumericVector prior_tau2, double tau2_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_Gumbeltau2updateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP prior_tau2SEXP, SEXP tau2_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_tau2(prior_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_tune(tau2_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Gumbeltau2updateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// GumbelrhoupdateRW
List GumbelrhoupdateRW(NumericMatrix Wtriplet, NumericVector Wtripletsum, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double rho_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_GumbelrhoupdateRW(SEXP WtripletSEXP, SEXP WtripletsumSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP rho_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wtripletsum(WtripletsumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type rho_tune(rho_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(GumbelrhoupdateRW(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// GumbelalphaupdateRW
List GumbelalphaupdateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double alpha_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_GumbelalphaupdateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP alpha_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_tune(alpha_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(GumbelalphaupdateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// ClaytonDensity2
double ClaytonDensity2(NumericVector LCDF, NumericVector CDF, double alpha, double nvar);
RcppExport SEXP _CARBayesCopula_ClaytonDensity2(SEXP LCDFSEXP, SEXP CDFSEXP, SEXP alphaSEXP, SEXP nvarSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type LCDF(LCDFSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type CDF(CDFSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type nvar(nvarSEXP);
    rcpp_result_gen = Rcpp::wrap(ClaytonDensity2(LCDF, CDF, alpha, nvar));
    return rcpp_result_gen;
END_RCPP
}
// binomialmcarupdateINVClaytonRW
List binomialmcarupdateINVClaytonRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericMatrix Y, NumericMatrix failures, NumericMatrix phioffset, NumericVector denoffset, NumericVector tau2, double alpha, double rho, double phi_tune);
RcppExport SEXP _CARBayesCopula_binomialmcarupdateINVClaytonRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP YSEXP, SEXP failuresSEXP, SEXP phioffsetSEXP, SEXP denoffsetSEXP, SEXP tau2SEXP, SEXP alphaSEXP, SEXP rhoSEXP, SEXP phi_tuneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type failures(failuresSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phioffset(phioffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type phi_tune(phi_tuneSEXP);
    rcpp_result_gen = Rcpp::wrap(binomialmcarupdateINVClaytonRW(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune));
    return rcpp_result_gen;
END_RCPP
}
// INVClaytontau2updateRW
List INVClaytontau2updateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, NumericVector prior_tau2, double tau2_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_INVClaytontau2updateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP prior_tau2SEXP, SEXP tau2_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_tau2(prior_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_tune(tau2_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(INVClaytontau2updateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// INVClaytonrhoupdateRW
List INVClaytonrhoupdateRW(NumericMatrix Wtriplet, NumericVector Wtripletsum, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double rho_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_INVClaytonrhoupdateRW(SEXP WtripletSEXP, SEXP WtripletsumSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP rho_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wtripletsum(WtripletsumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type rho_tune(rho_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(INVClaytonrhoupdateRW(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// INVClaytonalphaupdateRW
List INVClaytonalphaupdateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double alpha_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_INVClaytonalphaupdateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP alpha_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_tune(alpha_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(INVClaytonalphaupdateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// GumbelDensity2
double GumbelDensity2(NumericVector LCDF, double alpha);
RcppExport SEXP _CARBayesCopula_GumbelDensity2(SEXP LCDFSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type LCDF(LCDFSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(GumbelDensity2(LCDF, alpha));
    return rcpp_result_gen;
END_RCPP
}
// binomialmcarupdateINVGumbelRW
List binomialmcarupdateINVGumbelRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericMatrix Y, NumericMatrix failures, NumericMatrix phioffset, NumericVector denoffset, NumericVector tau2, double alpha, double rho, double phi_tune);
RcppExport SEXP _CARBayesCopula_binomialmcarupdateINVGumbelRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP YSEXP, SEXP failuresSEXP, SEXP phioffsetSEXP, SEXP denoffsetSEXP, SEXP tau2SEXP, SEXP alphaSEXP, SEXP rhoSEXP, SEXP phi_tuneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type failures(failuresSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phioffset(phioffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type phi_tune(phi_tuneSEXP);
    rcpp_result_gen = Rcpp::wrap(binomialmcarupdateINVGumbelRW(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune));
    return rcpp_result_gen;
END_RCPP
}
// INVGumbeltau2updateRW
List INVGumbeltau2updateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, NumericVector prior_tau2, double tau2_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_INVGumbeltau2updateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP prior_tau2SEXP, SEXP tau2_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_tau2(prior_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_tune(tau2_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(INVGumbeltau2updateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// INVGumbelrhoupdateRW
List INVGumbelrhoupdateRW(NumericMatrix Wtriplet, NumericVector Wtripletsum, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double rho_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_INVGumbelrhoupdateRW(SEXP WtripletSEXP, SEXP WtripletsumSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP rho_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wtripletsum(WtripletsumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type rho_tune(rho_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(INVGumbelrhoupdateRW(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// INVGumbelalphaupdateRW
List INVGumbelalphaupdateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double alpha_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_INVGumbelalphaupdateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP alpha_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_tune(alpha_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(INVGumbelalphaupdateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// JoeDensity2
double JoeDensity2(NumericVector CDF, double alpha);
RcppExport SEXP _CARBayesCopula_JoeDensity2(SEXP CDFSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type CDF(CDFSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(JoeDensity2(CDF, alpha));
    return rcpp_result_gen;
END_RCPP
}
// binomialmcarupdateINVJoeRW
List binomialmcarupdateINVJoeRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericMatrix Y, NumericMatrix failures, NumericMatrix phioffset, NumericVector denoffset, NumericVector tau2, double alpha, double rho, double phi_tune);
RcppExport SEXP _CARBayesCopula_binomialmcarupdateINVJoeRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP YSEXP, SEXP failuresSEXP, SEXP phioffsetSEXP, SEXP denoffsetSEXP, SEXP tau2SEXP, SEXP alphaSEXP, SEXP rhoSEXP, SEXP phi_tuneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type failures(failuresSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phioffset(phioffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type phi_tune(phi_tuneSEXP);
    rcpp_result_gen = Rcpp::wrap(binomialmcarupdateINVJoeRW(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune));
    return rcpp_result_gen;
END_RCPP
}
// INVJoetau2updateRW
List INVJoetau2updateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, NumericVector prior_tau2, double tau2_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_INVJoetau2updateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP prior_tau2SEXP, SEXP tau2_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_tau2(prior_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_tune(tau2_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(INVJoetau2updateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// INVJoerhoupdateRW
List INVJoerhoupdateRW(NumericMatrix Wtriplet, NumericVector Wtripletsum, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double rho_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_INVJoerhoupdateRW(SEXP WtripletSEXP, SEXP WtripletsumSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP rho_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wtripletsum(WtripletsumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type rho_tune(rho_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(INVJoerhoupdateRW(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// INVJoealphaupdateRW
List INVJoealphaupdateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double alpha_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_INVJoealphaupdateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP alpha_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_tune(alpha_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(INVJoealphaupdateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// JoeDensity
double JoeDensity(NumericVector CDF, double alpha);
RcppExport SEXP _CARBayesCopula_JoeDensity(SEXP CDFSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type CDF(CDFSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(JoeDensity(CDF, alpha));
    return rcpp_result_gen;
END_RCPP
}
// binomialmcarupdateJoeRW
List binomialmcarupdateJoeRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericMatrix Y, NumericMatrix failures, NumericMatrix phioffset, NumericVector denoffset, NumericVector tau2, double alpha, double rho, double phi_tune);
RcppExport SEXP _CARBayesCopula_binomialmcarupdateJoeRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP YSEXP, SEXP failuresSEXP, SEXP phioffsetSEXP, SEXP denoffsetSEXP, SEXP tau2SEXP, SEXP alphaSEXP, SEXP rhoSEXP, SEXP phi_tuneSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Y(YSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type failures(failuresSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phioffset(phioffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type phi_tune(phi_tuneSEXP);
    rcpp_result_gen = Rcpp::wrap(binomialmcarupdateJoeRW(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune));
    return rcpp_result_gen;
END_RCPP
}
// Joetau2updateRW
List Joetau2updateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, NumericVector prior_tau2, double tau2_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_Joetau2updateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP prior_tau2SEXP, SEXP tau2_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type prior_tau2(prior_tau2SEXP);
    Rcpp::traits::input_parameter< double >::type tau2_tune(tau2_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(Joetau2updateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// JoerhoupdateRW
List JoerhoupdateRW(NumericMatrix Wtriplet, NumericVector Wtripletsum, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double rho_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_JoerhoupdateRW(SEXP WtripletSEXP, SEXP WtripletsumSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP rho_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type Wtripletsum(WtripletsumSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type rho_tune(rho_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(JoerhoupdateRW(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}
// JoealphaupdateRW
List JoealphaupdateRW(NumericMatrix Wtriplet, NumericMatrix Wbegfin, const int nsites, const int nvar, NumericMatrix phi, NumericVector denoffset, double rho, double alpha_tune, NumericVector tau2, double alpha);
RcppExport SEXP _CARBayesCopula_JoealphaupdateRW(SEXP WtripletSEXP, SEXP WbegfinSEXP, SEXP nsitesSEXP, SEXP nvarSEXP, SEXP phiSEXP, SEXP denoffsetSEXP, SEXP rhoSEXP, SEXP alpha_tuneSEXP, SEXP tau2SEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type Wtriplet(WtripletSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type Wbegfin(WbegfinSEXP);
    Rcpp::traits::input_parameter< const int >::type nsites(nsitesSEXP);
    Rcpp::traits::input_parameter< const int >::type nvar(nvarSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type phi(phiSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type denoffset(denoffsetSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type alpha_tune(alpha_tuneSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type tau2(tau2SEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(JoealphaupdateRW(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_CARBayesCopula_matrixMultiply", (DL_FUNC) &_CARBayesCopula_matrixMultiply, 2},
    {"_CARBayesCopula_getDiagonal", (DL_FUNC) &_CARBayesCopula_getDiagonal, 1},
    {"_CARBayesCopula_linpredcompute", (DL_FUNC) &_CARBayesCopula_linpredcompute, 5},
    {"_CARBayesCopula_binomialbetaupdateRW", (DL_FUNC) &_CARBayesCopula_binomialbetaupdateRW, 12},
    {"_CARBayesCopula_binomialmcarupdateRW", (DL_FUNC) &_CARBayesCopula_binomialmcarupdateRW, 12},
    {"_CARBayesCopula_mcarrhoupdateRW", (DL_FUNC) &_CARBayesCopula_mcarrhoupdateRW, 10},
    {"_CARBayesCopula_gaussianmcarupdateRW", (DL_FUNC) &_CARBayesCopula_gaussianmcarupdateRW, 11},
    {"_CARBayesCopula_ClaytonDensity", (DL_FUNC) &_CARBayesCopula_ClaytonDensity, 4},
    {"_CARBayesCopula_binomialmcarupdateClaytonRW", (DL_FUNC) &_CARBayesCopula_binomialmcarupdateClaytonRW, 13},
    {"_CARBayesCopula_Claytontau2updateRW", (DL_FUNC) &_CARBayesCopula_Claytontau2updateRW, 11},
    {"_CARBayesCopula_ClaytonrhoupdateRW", (DL_FUNC) &_CARBayesCopula_ClaytonrhoupdateRW, 11},
    {"_CARBayesCopula_ClaytonalphaupdateRW", (DL_FUNC) &_CARBayesCopula_ClaytonalphaupdateRW, 10},
    {"_CARBayesCopula_FrankDensity", (DL_FUNC) &_CARBayesCopula_FrankDensity, 3},
    {"_CARBayesCopula_binomialmcarupdateFrankRW", (DL_FUNC) &_CARBayesCopula_binomialmcarupdateFrankRW, 13},
    {"_CARBayesCopula_Franktau2updateRW", (DL_FUNC) &_CARBayesCopula_Franktau2updateRW, 11},
    {"_CARBayesCopula_FrankrhoupdateRW", (DL_FUNC) &_CARBayesCopula_FrankrhoupdateRW, 11},
    {"_CARBayesCopula_FrankalphaupdateRW", (DL_FUNC) &_CARBayesCopula_FrankalphaupdateRW, 10},
    {"_CARBayesCopula_GaussianDensity", (DL_FUNC) &_CARBayesCopula_GaussianDensity, 3},
    {"_CARBayesCopula_binomialmcarupdateGaussianRW", (DL_FUNC) &_CARBayesCopula_binomialmcarupdateGaussianRW, 13},
    {"_CARBayesCopula_Gaussiantau2updateRW", (DL_FUNC) &_CARBayesCopula_Gaussiantau2updateRW, 11},
    {"_CARBayesCopula_GaussianrhoupdateRW", (DL_FUNC) &_CARBayesCopula_GaussianrhoupdateRW, 11},
    {"_CARBayesCopula_GaussianalphaupdateRW", (DL_FUNC) &_CARBayesCopula_GaussianalphaupdateRW, 10},
    {"_CARBayesCopula_GumbelDensity", (DL_FUNC) &_CARBayesCopula_GumbelDensity, 2},
    {"_CARBayesCopula_binomialmcarupdateGumbelRW", (DL_FUNC) &_CARBayesCopula_binomialmcarupdateGumbelRW, 13},
    {"_CARBayesCopula_Gumbeltau2updateRW", (DL_FUNC) &_CARBayesCopula_Gumbeltau2updateRW, 11},
    {"_CARBayesCopula_GumbelrhoupdateRW", (DL_FUNC) &_CARBayesCopula_GumbelrhoupdateRW, 11},
    {"_CARBayesCopula_GumbelalphaupdateRW", (DL_FUNC) &_CARBayesCopula_GumbelalphaupdateRW, 10},
    {"_CARBayesCopula_ClaytonDensity2", (DL_FUNC) &_CARBayesCopula_ClaytonDensity2, 4},
    {"_CARBayesCopula_binomialmcarupdateINVClaytonRW", (DL_FUNC) &_CARBayesCopula_binomialmcarupdateINVClaytonRW, 13},
    {"_CARBayesCopula_INVClaytontau2updateRW", (DL_FUNC) &_CARBayesCopula_INVClaytontau2updateRW, 11},
    {"_CARBayesCopula_INVClaytonrhoupdateRW", (DL_FUNC) &_CARBayesCopula_INVClaytonrhoupdateRW, 11},
    {"_CARBayesCopula_INVClaytonalphaupdateRW", (DL_FUNC) &_CARBayesCopula_INVClaytonalphaupdateRW, 10},
    {"_CARBayesCopula_GumbelDensity2", (DL_FUNC) &_CARBayesCopula_GumbelDensity2, 2},
    {"_CARBayesCopula_binomialmcarupdateINVGumbelRW", (DL_FUNC) &_CARBayesCopula_binomialmcarupdateINVGumbelRW, 13},
    {"_CARBayesCopula_INVGumbeltau2updateRW", (DL_FUNC) &_CARBayesCopula_INVGumbeltau2updateRW, 11},
    {"_CARBayesCopula_INVGumbelrhoupdateRW", (DL_FUNC) &_CARBayesCopula_INVGumbelrhoupdateRW, 11},
    {"_CARBayesCopula_INVGumbelalphaupdateRW", (DL_FUNC) &_CARBayesCopula_INVGumbelalphaupdateRW, 10},
    {"_CARBayesCopula_JoeDensity2", (DL_FUNC) &_CARBayesCopula_JoeDensity2, 2},
    {"_CARBayesCopula_binomialmcarupdateINVJoeRW", (DL_FUNC) &_CARBayesCopula_binomialmcarupdateINVJoeRW, 13},
    {"_CARBayesCopula_INVJoetau2updateRW", (DL_FUNC) &_CARBayesCopula_INVJoetau2updateRW, 11},
    {"_CARBayesCopula_INVJoerhoupdateRW", (DL_FUNC) &_CARBayesCopula_INVJoerhoupdateRW, 11},
    {"_CARBayesCopula_INVJoealphaupdateRW", (DL_FUNC) &_CARBayesCopula_INVJoealphaupdateRW, 10},
    {"_CARBayesCopula_JoeDensity", (DL_FUNC) &_CARBayesCopula_JoeDensity, 2},
    {"_CARBayesCopula_binomialmcarupdateJoeRW", (DL_FUNC) &_CARBayesCopula_binomialmcarupdateJoeRW, 13},
    {"_CARBayesCopula_Joetau2updateRW", (DL_FUNC) &_CARBayesCopula_Joetau2updateRW, 11},
    {"_CARBayesCopula_JoerhoupdateRW", (DL_FUNC) &_CARBayesCopula_JoerhoupdateRW, 11},
    {"_CARBayesCopula_JoealphaupdateRW", (DL_FUNC) &_CARBayesCopula_JoealphaupdateRW, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_CARBayesCopula(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
