# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matrixMultiply <- function(mat1, mat2) {
    .Call('_CARBayesCopula_matrixMultiply', PACKAGE = 'CARBayesCopula', mat1, mat2)
}

getDiagonal <- function(mat) {
    .Call('_CARBayesCopula_getDiagonal', PACKAGE = 'CARBayesCopula', mat)
}

linpredcompute <- function(X, nsites, p, beta, offset) {
    .Call('_CARBayesCopula_linpredcompute', PACKAGE = 'CARBayesCopula', X, nsites, p, beta, offset)
}

binomialbetaupdateRW <- function(X, nsites, p, beta, offset, y, failures, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list) {
    .Call('_CARBayesCopula_binomialbetaupdateRW', PACKAGE = 'CARBayesCopula', X, nsites, p, beta, offset, y, failures, prior_meanbeta, prior_varbeta, nblock, beta_tune, block_list)
}

binomialmcarupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, Sigmainv, rho, phi_tune) {
    .Call('_CARBayesCopula_binomialmcarupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, Sigmainv, rho, phi_tune)
}

mcarrhoupdateRW <- function(Wstar, Wstar_val, K, J, rho, Q, det_Q, proposal_sd_rho, phi, Sigma_inv) {
    .Call('_CARBayesCopula_mcarrhoupdateRW', PACKAGE = 'CARBayesCopula', Wstar, Wstar_val, K, J, rho, Q, det_Q, proposal_sd_rho, phi, Sigma_inv)
}

gaussianmcarupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, phioffset, denoffset, Sigmainv, rho, nu2, phi_tune) {
    .Call('_CARBayesCopula_gaussianmcarupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, phioffset, denoffset, Sigmainv, rho, nu2, phi_tune)
}

ClaytonDensity <- function(LCDF, CDF, alpha, nvar) {
    .Call('_CARBayesCopula_ClaytonDensity', PACKAGE = 'CARBayesCopula', LCDF, CDF, alpha, nvar)
}

binomialmcarupdateClaytonRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune) {
    .Call('_CARBayesCopula_binomialmcarupdateClaytonRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune)
}

Claytontau2updateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha) {
    .Call('_CARBayesCopula_Claytontau2updateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha)
}

ClaytonrhoupdateRW <- function(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha) {
    .Call('_CARBayesCopula_ClaytonrhoupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha)
}

ClaytonalphaupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha) {
    .Call('_CARBayesCopula_ClaytonalphaupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha)
}

FrankDensity <- function(CDF, alpha, nvar) {
    .Call('_CARBayesCopula_FrankDensity', PACKAGE = 'CARBayesCopula', CDF, alpha, nvar)
}

binomialmcarupdateFrankRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune) {
    .Call('_CARBayesCopula_binomialmcarupdateFrankRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune)
}

Franktau2updateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha) {
    .Call('_CARBayesCopula_Franktau2updateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha)
}

FrankrhoupdateRW <- function(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha) {
    .Call('_CARBayesCopula_FrankrhoupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha)
}

FrankalphaupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha) {
    .Call('_CARBayesCopula_FrankalphaupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha)
}

GaussianDensity <- function(CDF_q, alpha, nvar) {
    .Call('_CARBayesCopula_GaussianDensity', PACKAGE = 'CARBayesCopula', CDF_q, alpha, nvar)
}

binomialmcarupdateGaussianRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune) {
    .Call('_CARBayesCopula_binomialmcarupdateGaussianRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune)
}

Gaussiantau2updateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha) {
    .Call('_CARBayesCopula_Gaussiantau2updateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha)
}

GaussianrhoupdateRW <- function(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha) {
    .Call('_CARBayesCopula_GaussianrhoupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha)
}

GaussianalphaupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha) {
    .Call('_CARBayesCopula_GaussianalphaupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha)
}

GumbelDensity <- function(LCDF, alpha) {
    .Call('_CARBayesCopula_GumbelDensity', PACKAGE = 'CARBayesCopula', LCDF, alpha)
}

binomialmcarupdateGumbelRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune) {
    .Call('_CARBayesCopula_binomialmcarupdateGumbelRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune)
}

Gumbeltau2updateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha) {
    .Call('_CARBayesCopula_Gumbeltau2updateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha)
}

GumbelrhoupdateRW <- function(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha) {
    .Call('_CARBayesCopula_GumbelrhoupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha)
}

GumbelalphaupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha) {
    .Call('_CARBayesCopula_GumbelalphaupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha)
}

ClaytonDensity2 <- function(LCDF, CDF, alpha, nvar) {
    .Call('_CARBayesCopula_ClaytonDensity2', PACKAGE = 'CARBayesCopula', LCDF, CDF, alpha, nvar)
}

binomialmcarupdateINVClaytonRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune) {
    .Call('_CARBayesCopula_binomialmcarupdateINVClaytonRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune)
}

INVClaytontau2updateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha) {
    .Call('_CARBayesCopula_INVClaytontau2updateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha)
}

INVClaytonrhoupdateRW <- function(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha) {
    .Call('_CARBayesCopula_INVClaytonrhoupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha)
}

INVClaytonalphaupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha) {
    .Call('_CARBayesCopula_INVClaytonalphaupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha)
}

GumbelDensity2 <- function(LCDF, alpha) {
    .Call('_CARBayesCopula_GumbelDensity2', PACKAGE = 'CARBayesCopula', LCDF, alpha)
}

binomialmcarupdateINVGumbelRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune) {
    .Call('_CARBayesCopula_binomialmcarupdateINVGumbelRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune)
}

INVGumbeltau2updateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha) {
    .Call('_CARBayesCopula_INVGumbeltau2updateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha)
}

INVGumbelrhoupdateRW <- function(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha) {
    .Call('_CARBayesCopula_INVGumbelrhoupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha)
}

INVGumbelalphaupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha) {
    .Call('_CARBayesCopula_INVGumbelalphaupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha)
}

JoeDensity2 <- function(CDF, alpha) {
    .Call('_CARBayesCopula_JoeDensity2', PACKAGE = 'CARBayesCopula', CDF, alpha)
}

binomialmcarupdateINVJoeRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune) {
    .Call('_CARBayesCopula_binomialmcarupdateINVJoeRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune)
}

INVJoetau2updateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha) {
    .Call('_CARBayesCopula_INVJoetau2updateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha)
}

INVJoerhoupdateRW <- function(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha) {
    .Call('_CARBayesCopula_INVJoerhoupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha)
}

INVJoealphaupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha) {
    .Call('_CARBayesCopula_INVJoealphaupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha)
}

JoeDensity <- function(CDF, alpha) {
    .Call('_CARBayesCopula_JoeDensity', PACKAGE = 'CARBayesCopula', CDF, alpha)
}

binomialmcarupdateJoeRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune) {
    .Call('_CARBayesCopula_binomialmcarupdateJoeRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, Y, failures, phioffset, denoffset, tau2, alpha, rho, phi_tune)
}

Joetau2updateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha) {
    .Call('_CARBayesCopula_Joetau2updateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, prior_tau2, tau2_tune, tau2, alpha)
}

JoerhoupdateRW <- function(Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha) {
    .Call('_CARBayesCopula_JoerhoupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wtripletsum, Wbegfin, nsites, nvar, phi, denoffset, rho, rho_tune, tau2, alpha)
}

JoealphaupdateRW <- function(Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha) {
    .Call('_CARBayesCopula_JoealphaupdateRW', PACKAGE = 'CARBayesCopula', Wtriplet, Wbegfin, nsites, nvar, phi, denoffset, rho, alpha_tune, tau2, alpha)
}

